apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 80        # External port exposed by the service
      targetPort: 8080 # Port where your Spring Boot app is listening inside the pod
  type: NodePort  # Type of service (use NodePort or ClusterIP if needed)
